name: coffee_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  cached_network_image: ^3.2.3
  coffee_repository:
    path: packages/coffee_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  gallery_saver: ^2.3.2
  gap: ^2.0.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0
  image_saver_wrapper:
    path: packages/image_saver_wrapper
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  test: ^1.21.4

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/